# Generated by Django 2.2.2 on 2019-06-14 20:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('duration', models.IntegerField(null=True)),
                ('year', models.IntegerField()),
                ('poster', models.ImageField(upload_to='')),
                ('detail', models.TextField()),
                ('classification', models.CharField(choices=[('A', 'para todo publico'), ('B', '12 años en adelante'), ('B15', '15 años en adelante'), ('C', '18 años en adelante'), ('D', 'para adultos')], max_length=5)),
                ('trailer_url', models.URLField()),
                ('genre', models.CharField(default=None, max_length=20)),
                ('rating', models.FloatField()),
                ('original_language', models.CharField(max_length=20)),
                ('release_date', models.DateField(null=True)),
                ('country', models.CharField(max_length=20)),
                ('slug', models.CharField(blank=True, max_length=70, null=True)),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Actor')),
                ('directors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieDirector')),
            ],
        ),
        migrations.CreateModel(
            name='MovieRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(default=0.0)),
                ('comment', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('can_vote_two_times', 'Can vote two times'),),
                'unique_together': {('users', 'movie')},
            },
        ),
    ]
