# Generated by Django 2.2.1 on 2019-06-07 15:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70)),
                ('duration', models.TimeField()),
                ('year', models.IntegerField()),
                ('poster', models.ImageField(upload_to='')),
                ('detail', models.TextField()),
                ('classification', models.CharField(choices=[('para todo publico', 'A'), ('12 años en adelante', 'B'), ('15 años en adelante', 'B15'), ('18 años en adelante', 'C'), ('para adultos', 'D')], max_length=5)),
                ('trailer_url', models.URLField()),
                ('rating', models.FloatField()),
                ('original_language', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('country', models.CharField(max_length=20)),
                ('actors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Actor')),
            ],
        ),
        migrations.CreateModel(
            name='MovieDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MovieRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
                ('users', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='directors',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.MovieDirector'),
        ),
    ]
