# Generated by Django 2.2.1 on 2019-06-10 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='movierate',
            name='rate',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='movie',
            name='classification',
            field=models.CharField(choices=[('A', 'para todo publico'), ('B', '12 años en adelante'), ('B15', '15 años en adelante'), ('C', '18 años en adelante'), ('D', 'para adultos')], max_length=5),
        ),
    ]
