# Generated by Django 2.2.1 on 2019-06-12 13:23

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_auto_20190610_2007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movierate',
            options={'permissions': (('can_vote_two_times', 'Can vote two times'),)},
        ),
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='movierate',
            unique_together={('users', 'movie')},
        ),
    ]
