# Generated by Django 2.2.2 on 2019-06-14 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20190614_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='moviedirector',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
