# Generated by Django 2.2.2 on 2019-06-17 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190614_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='country',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='movie',
            name='original_language',
            field=models.CharField(max_length=100),
        ),
    ]
